### ISSUE TITLE
USER STORY : Community participation

### ISSUE THREAD

**Issue by Ygallo** [Ygallo/My-First-Agile-Project#3]
As a **runner part of the Love running community** I can **choose options on a poll** so that **provide my opinion about different running topics**.

### **Acceptance Criteria**:

- **Acceptance Criteria 1**: Have a drop-down menu on the poll.
- **Acceptance Criteria 2**:  The drop-down must have at least 3 options to choose from
- **Acceptance Criteria 3**: Have the option to leave also a comment. 

### **Tasks**
- [ ] Create the poll question with a drop-down menu
- [ ] Highlight the drop-down selection
- [ ] Create a pop-up message to confirm the Selection
- [ ] Add an optional comment box to submit any added comments
